AY2425S2-CS2103-F08-3/tp

docs/DeveloperGuide.md

Fix use case extension numbering in developer guide

---

src/main/java/seedu/address/model/price/Price.java

Add price class for future Listing model

---

src/main/java/seedu/address/model/listing/Listing.java

Fixes #66 
Does not contain test cases.

Add listing class

---

src/main/java/seedu/address/model/listing/UniqueListingList.java
src/main/java/seedu/address/model/listing/exceptions/DuplicateListingException.java
src/main/java/seedu/address/model/listing/exceptions/ListingNotFoundException.java

Fixes #68
Does not contain test cases.

Add unique listing list

---

src/main/resources/view/PersonListPanel.fxml

Update Person listing UI

---

src/main/java/seedu/address/logic/Logic.java
src/main/java/seedu/address/logic/LogicManager.java
src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/AddListingCommand.java
src/main/java/seedu/address/logic/parser/AddListingCommandParser.java
src/main/java/seedu/address/logic/parser/AddPersonCommandParser.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/ReadOnlyAddressBook.java
src/main/java/seedu/address/ui/MainWindow.java
src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java
src/test/java/seedu/address/model/AddressBookTest.java

Add addListingCommand

---

src/main/java/seedu/address/model/person/PropertyPreference.java

Add Property Preference class

---

src/main/java/seedu/address/logic/commands/ListListingCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/model/Model.java

Add property list command

---

src/main/java/seedu/address/logic/commands/ListPersonCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/test/java/seedu/address/logic/LogicManagerTest.java
src/test/java/seedu/address/logic/commands/ListPersonCommandTest.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java

Add person list command

---

src/main/java/seedu/address/logic/Logic.java
src/main/java/seedu/address/logic/LogicManager.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/java/seedu/address/ui/TagListPanel.java
src/main/resources/view/MainWindow.fxml
src/main/resources/view/TagListPanel.fxml
src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java

Fixes #95 
Does not include new test cases.

Add tag list UI

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/AddTagCommand.java
src/main/java/seedu/address/logic/parser/AddTagCommandParser.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java

Add tag command

---

src/main/java/seedu/address/logic/commands/AddTagCommand.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/person/PropertyPreference.java
src/main/java/seedu/address/model/tag/Tag.java
src/main/java/seedu/address/model/tag/TagRegistry.java
src/main/java/seedu/address/storage/JsonAdaptedTag.java
src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java
src/test/java/seedu/address/model/AddressBookTest.java
src/test/java/seedu/address/model/person/PersonTest.java
src/test/java/seedu/address/model/tag/TagRegistryTest.java
src/test/java/seedu/address/model/tag/TagTest.java

Add tags to property preferences, and vice versa

---

src/main/java/seedu/address/logic/Logic.java
src/main/java/seedu/address/logic/LogicManager.java
src/main/java/seedu/address/logic/commands/ListTagCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/ui/TagListPanel.java
src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java

Add list tag command

---

src/main/java/seedu/address/logic/commands/EditPersonCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/EditPersonCommandParser.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/EditPersonCommandTest.java
src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
src/test/java/seedu/address/logic/parser/EditPersonCommandParserTest.java
src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
src/test/java/seedu/address/testutil/PersonUtil.java

Edit person command

---

src/main/java/seedu/address/ui/HelpWindow.java

Update command list in help window

---

src/main/java/seedu/address/logic/commands/AddListingCommand.java
src/main/java/seedu/address/model/listing/Listing.java
src/main/java/seedu/address/model/tag/Tag.java

Remove associations from equals function

---

src/main/java/seedu/address/logic/commands/AddListingCommand.java
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/listing/Listing.java
src/test/java/seedu/address/logic/LogicManagerTest.java
src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java

Add delete person command

---

src/main/java/seedu/address/storage/JsonAdaptedListing.java
src/main/java/seedu/address/storage/JsonAdaptedPerson.java
src/main/java/seedu/address/storage/JsonAdaptedPreference.java
src/main/java/seedu/address/storage/JsonAdaptedPriceRange.java
src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java

Add persistent storage

---

src/main/java/seedu/address/logic/parser/AddPreferenceCommandParser.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/resources/view/PersonListCard.fxml

Add property preference command

---

src/main/java/seedu/address/ui/ListingCard.java
src/main/java/seedu/address/ui/OwnerCard.java
src/main/java/seedu/address/ui/OwnerListPanel.java
src/main/resources/view/OwnerListCard.fxml
src/main/resources/view/OwnerListPanel.fxml

Add listing owners UI

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/DeleteOwnerCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/DeleteOwnerCommandParser.java
src/main/java/seedu/address/storage/JsonSerializableAddressBook.java

Add deleteOwner command

---

src/main/java/seedu/address/storage/JsonAdaptedListing.java

Fix storage of listing with no property name

---

src/main/java/seedu/address/ui/TagListPanel.java

Add tag counter in UI

---

src/main/java/seedu/address/storage/JsonSerializableAddressBook.java

Fix tags association upon initialization

---

src/main/java/seedu/address/model/listing/Listing.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/person/PropertyPreference.java
src/main/java/seedu/address/model/tag/Tag.java

Fix model equal function to not contain associations 

---

src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/ui/HelpWindow.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java

Disable editPerson and clear commands

---

src/main/java/seedu/address/model/listing/Listing.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/person/PropertyPreference.java
src/main/java/seedu/address/model/tag/Tag.java

Remove immutability from associations in models

---

src/main/java/seedu/address/logic/commands/AssignListingCommand.java

Able to assign same Person as Listing owner multiple times

---

src/main/java/seedu/address/logic/commands/AssignListingCommand.java
src/main/java/seedu/address/storage/JsonAdaptedListing.java
src/main/java/seedu/address/storage/JsonAdaptedPerson.java
src/main/java/seedu/address/storage/JsonAdaptedPreference.java
src/main/java/seedu/address/storage/JsonAdaptedTag.java
src/main/java/seedu/address/storage/JsonSerializableAddressBook.java

Update storage initialization with new mutable models

---

src/main/java/seedu/address/logic/commands/ClearCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java

Update clear command

---

src/main/java/seedu/address/logic/commands/FindPersonCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/FindPersonCommandParser.java
src/main/java/seedu/address/ui/HelpWindow.java
src/test/java/seedu/address/logic/commands/FindPersonCommandTest.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
src/test/java/seedu/address/logic/parser/FindPersonCommandParserTest.java

Rename findCommand to findPersonCommand

---

src/main/java/seedu/address/logic/commands/DeletePersonCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
src/test/java/seedu/address/logic/commands/DeletePersonCommandTest.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
src/test/java/seedu/address/logic/parser/DeletePersonCommandParserTest.java

Rename deleteCommand to deletePersonCommand

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/DeletePreferenceTagCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/DeletePreferenceTagCommandParser.java

Add delete preference tag command

---

src/main/java/seedu/address/logic/commands/DeleteListingCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/DeleteListingCommandParser.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java

Add delete property command

---

src/main/java/seedu/address/logic/commands/AddPreferenceTagCommand.java
src/main/java/seedu/address/logic/parser/AddPreferenceTagCommandParser.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java

Add add preference tag command

---

src/main/java/seedu/address/logic/parser/AddPreferenceTagCommandParser.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/AssignListingCommandParser.java
src/main/java/seedu/address/logic/parser/DeleteOwnerCommandParser.java
src/main/java/seedu/address/logic/parser/DeletePersonCommandParser.java
src/main/java/seedu/address/logic/parser/DeletePreferenceTagCommandParser.java
src/test/java/seedu/address/logic/parser/DeletePersonCommandParserTest.java

Fix bug where no exception thrown when 1 index is provided for command where 2 indices is required

---

src/main/java/seedu/address/logic/commands/OverwritePreferenceTagCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/OverwritePreferenceTagCommandParser.java

Add overwrite tags to property preference command

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/SearchPropertyByTagCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/SearchPropertyByTagCommandParser.java
src/main/java/seedu/address/model/listing/predicates/ListingContainsAllTagsPredicate.java
src/test/java/seedu/address/logic/commands/SearchPropertyByTagCommandTest.java
src/test/java/seedu/address/model/listing/predicates/ListingContainsAllTagsPredicateTest.java

Search property by tags

---

src/main/java/seedu/address/logic/commands/EditPersonCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/model/person/PropertyPreference.java
src/test/java/seedu/address/logic/commands/EditPersonCommandTest.java

Update edit person command mutability

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/AddListingCommand.java
src/main/java/seedu/address/logic/commands/MarkAvailableCommand.java
src/main/java/seedu/address/logic/commands/MarkUnavailableCommand.java
src/main/java/seedu/address/logic/parser/AddListingCommandParser.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/MarkAvailableCommandParser.java
src/main/java/seedu/address/logic/parser/MarkUnavailableCommandParser.java
src/main/java/seedu/address/model/listing/Listing.java
src/main/java/seedu/address/storage/JsonAdaptedListing.java
src/main/java/seedu/address/ui/ListingCard.java
src/main/resources/view/ListingListCard.fxml
src/test/java/seedu/address/logic/commands/DeletePropertyTagCommandTest.java
src/test/java/seedu/address/logic/commands/SearchPropertyByTagCommandTest.java
src/test/java/seedu/address/logic/parser/DeletePersonCommandParserTest.java
src/test/java/seedu/address/logic/parser/EditPersonCommandParserTest.java
src/test/java/seedu/address/model/listing/predicates/ListingContainsAllTagsPredicateTest.java
src/test/java/seedu/address/model/tag/TagRegistryTest.java

Fixes #207 
Above shows Listing currently unavailable.
Above shows Listing is available after MarkAvailableCommand.

Mark a property as available

---

src/main/java/seedu/address/logic/commands/DeletePropertyTagCommand.java
src/main/java/seedu/address/logic/commands/SearchPropertyByTagCommand.java
src/main/java/seedu/address/logic/parser/DeletePropertyTagCommandParser.java
src/main/java/seedu/address/logic/parser/SearchPropertyByTagCommandParser.java
src/test/java/seedu/address/logic/commands/DeletePropertyTagCommandTest.java
src/test/java/seedu/address/logic/parser/DeletePropertyTagCommandParserTest.java
src/test/java/seedu/address/logic/parser/SearchPropertyByTagCommandParserTest.java

Fix commands not responding to missing prefixes and arguments

---

src/main/java/seedu/address/ui/HelpWindow.java
src/main/resources/view/HelpWindow.fxml

Update help command with new v1.4 commands

---

docs/DeveloperGuide.md
docs/diagrams/UiClassDiagram.puml
src/main/java/seedu/address/ui/PreferenceCard.java
src/main/java/seedu/address/ui/PreferenceListPanel.java

Update UI CD

---

src/main/java/seedu/address/ui/HelpWindow.java

Fix help window focus when minimized

---

src/main/java/seedu/address/logic/parser/MarkAvailableCommandParser.java
src/main/java/seedu/address/logic/parser/MarkUnavailableCommandParser.java
src/main/java/seedu/address/logic/parser/MatchListingCommandParser.java
src/main/java/seedu/address/logic/parser/MatchPersonCommandParser.java
src/main/java/seedu/address/model/price/Price.java
src/main/java/seedu/address/storage/JsonAdaptedPriceRange.java

Fixes #310 
matchListing 2
matchPerson 1 2

Fix price to handle large values

---

src/main/resources/view/PersonListPanel.fxml

Rename person list UI label from Clients to Persons

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/parser/AddListingCommandParser.java
src/main/java/seedu/address/logic/parser/AddPreferenceCommandParser.java

Fix exception for lower bound price bigger than upper bound price

---

src/main/java/seedu/address/commons/util/CommandUtil.java
src/main/java/seedu/address/logic/commands/AddPreferenceTagCommand.java
src/main/java/seedu/address/logic/commands/DeleteListingCommand.java
src/main/java/seedu/address/logic/commands/DeletePreferenceTagCommand.java
src/main/java/seedu/address/logic/commands/OverwriteListingTagCommand.java
src/main/java/seedu/address/logic/commands/OverwritePreferenceTagCommand.java
src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
src/main/java/seedu/address/logic/parser/DeleteListingTagCommandParser.java
src/main/java/seedu/address/logic/parser/DeleteOwnerCommandParser.java
src/main/java/seedu/address/logic/parser/DeletePreferenceCommandParser.java
src/main/java/seedu/address/logic/parser/DeletePreferenceTagCommandParser.java
src/main/java/seedu/address/logic/parser/EditPersonCommandParser.java
src/main/java/seedu/address/logic/parser/MatchPreferenceCommandParser.java
src/main/java/seedu/address/logic/parser/OverwriteListingTagCommandParser.java
src/main/java/seedu/address/logic/parser/OverwritePreferenceTagCommandParser.java
src/main/java/seedu/address/logic/parser/Prefix.java
src/main/java/seedu/address/model/price/PriceRange.java
src/main/java/seedu/address/model/search/comparators/ListingPreferenceScoreComparator.java
src/main/java/seedu/address/model/search/comparators/PersonListingScoreComparator.java
src/main/java/seedu/address/ui/ListingCard.java
src/main/java/seedu/address/ui/ListingListPanel.java
src/main/java/seedu/address/ui/OwnerListPanel.java
src/main/java/seedu/address/ui/PersonListPanel.java
src/main/java/seedu/address/ui/PreferenceListPanel.java

Improve code quality

---

src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/listing/HouseNumber.java
src/main/java/seedu/address/model/listing/Listing.java
src/main/java/seedu/address/model/listing/PostalCode.java
src/main/java/seedu/address/model/listing/PropertyName.java
src/main/java/seedu/address/model/listing/UniqueListingList.java
src/main/java/seedu/address/model/listing/UnitNumber.java
src/main/java/seedu/address/model/listing/exceptions/DuplicateListingException.java
src/main/java/seedu/address/model/person/Email.java
src/main/java/seedu/address/model/person/Name.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/person/Phone.java
src/main/java/seedu/address/model/person/PropertyPreference.java
src/main/java/seedu/address/model/person/exceptions/DuplicatePersonException.java
src/main/java/seedu/address/model/price/Price.java
src/main/java/seedu/address/model/price/PriceRange.java
src/main/java/seedu/address/model/tag/Tag.java
src/main/java/seedu/address/model/tag/UniqueTagMap.java
src/main/java/seedu/address/model/tag/exceptions/DuplicateTagException.java

Standardize javaDocs for model component

---

src/main/java/seedu/address/logic/commands/SearchPersonByName.java
src/main/java/seedu/address/logic/parser/SearchPersonByNameParser.java
src/test/java/seedu/address/logic/commands/SearchPersonByNameTest.java
src/test/java/seedu/address/logic/parser/SearchPersonByNameParserTest.java

Shift logic in searchPersonByNameCommand to parser

---

docs/DeveloperGuide.md

Fix use cases

---

docs/DeveloperGuide.md

Fix developer guide formatting

---

src/main/java/seedu/address/logic/commands/AddListingTagCommand.java
src/main/java/seedu/address/logic/commands/AddOwnerCommand.java
src/main/java/seedu/address/logic/commands/AddPreferenceCommand.java
src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
src/main/java/seedu/address/logic/commands/EditPersonCommand.java
src/main/java/seedu/address/logic/commands/MarkAvailableCommand.java
src/main/java/seedu/address/logic/commands/MarkUnavailableCommand.java
src/main/java/seedu/address/logic/commands/OverwriteListingTagCommand.java
src/main/java/seedu/address/logic/commands/OverwritePreferenceTagCommand.java
src/main/java/seedu/address/logic/commands/SearchListingByTagCommand.java
src/main/java/seedu/address/logic/commands/SearchPersonByTagCommand.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/listing/Listing.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/person/PropertyPreference.java
src/main/java/seedu/address/model/price/Price.java
src/main/java/seedu/address/model/price/PriceRange.java
src/test/java/seedu/address/logic/commands/EditPersonCommandTest.java
src/test/java/seedu/address/model/AddressBookTest.java
src/test/java/seedu/address/model/person/PersonTest.java

Fixes #353 
Note that the new predicate classes do not have toString defined in them.

Add toString methods to commands

---

src/main/java/seedu/address/logic/commands/SearchPersonByNameCommand.java
src/main/java/seedu/address/logic/commands/SearchPersonByTagCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/SearchPersonByNameCommandParser.java
src/main/java/seedu/address/ui/HelpWindow.java
src/test/java/seedu/address/logic/commands/SearchPersonByNameCommandTest.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
src/test/java/seedu/address/logic/parser/SearchPersonByNameCommandParserTest.java

Rename SearchPersonByName to SearchPersonByNameCommand

---

docs/DeveloperGuide.md

Update DG with MergeTagSequenceDiagram

---

src/main/java/seedu/address/logic/commands/ClearCommand.java

Rename clear command success message

---

src/main/java/seedu/address/commons/util/CommandUtil.java
src/main/java/seedu/address/logic/commands/AddListingCommand.java
src/main/java/seedu/address/logic/commands/AddListingTagCommand.java
src/main/java/seedu/address/logic/commands/AddOwnerCommand.java
src/main/java/seedu/address/logic/commands/AddPreferenceCommand.java
src/main/java/seedu/address/logic/commands/DeleteListingCommand.java
src/main/java/seedu/address/logic/commands/DeleteListingTagCommand.java
src/main/java/seedu/address/logic/commands/DeleteOwnerCommand.java
src/main/java/seedu/address/logic/commands/DeletePersonCommand.java
src/main/java/seedu/address/logic/commands/DeletePreferenceCommand.java
src/main/java/seedu/address/logic/commands/EditPersonCommand.java
src/main/java/seedu/address/logic/commands/MarkAvailableCommand.java
src/main/java/seedu/address/logic/commands/MarkUnavailableCommand.java
src/main/java/seedu/address/logic/commands/MatchListingCommand.java
src/main/java/seedu/address/logic/commands/MatchPreferenceCommand.java
src/main/java/seedu/address/logic/commands/OverwriteListingTagCommand.java
src/main/java/seedu/address/logic/commands/SearchOwnerListingCommand.java
src/main/java/seedu/address/logic/commands/SearchPersonByTagCommand.java

Further improve code quality

---

src/main/java/seedu/address/model/listing/UnitNumber.java
src/main/java/seedu/address/model/person/Phone.java

Update unit number regex

---

docs/DeveloperGuide.md

Update glossary in developer guide

---

src/main/java/seedu/address/model/search/comparators/DefaultListingComparator.java
src/main/java/seedu/address/model/search/comparators/ListingPreferenceScoreComparator.java
src/main/java/seedu/address/model/search/comparators/PersonListingScoreComparator.java
src/main/java/seedu/address/model/search/predicates/ListingMatchesPreferencePredicate.java
src/main/java/seedu/address/model/search/predicates/PersonMatchesPropertyPredicate.java

Improve code quality for search models

---

.gitignore
docs/_markbind/layouts/default.md

Update navbar to remove tutorials section

---

src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/search/comparators/DefaultPersonComparator.java

Fix person sorting

---

docs/UserGuide.md
docs/index.md
src/main/java/seedu/address/logic/commands/AddPreferenceTagCommand.java
src/main/java/seedu/address/model/person/Email.java

Fixes #472 
Fixes #414 
Fixes #439

Update UG application brief description

---

docs/DeveloperGuide.md

Fix use case extension repetition in developer guide

---

docs/DeveloperGuide.md
docs/diagrams/EditPreferenceSequenceDiagram.puml

Fixes #480 
Edit preference sequence diagram

add editPreferenceSequenceDiagram

---

docs/DeveloperGuide.md

Add tag filtering consideration in DG

---

docs/UserGuide.md

Add more example commands to user guide
